# Audio beep test only — do not reuse the full JS XDC (HDMI/SD/FT245/DDR3).
# Pins from Digilent Nexys-Video-Master.xdc (audio codec section, J5).
# Same discipline as tools/pmod_input_test: this file constrains a tiny
# standalone design and must never be added to tools/board_flow.

set_property -dict { PACKAGE_PIN R4  IOSTANDARD LVCMOS33 } [get_ports { clk100 }]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports { clk100 }]

set_property -dict { PACKAGE_PIN G4  IOSTANDARD LVCMOS15 } [get_ports { cpu_resetn }]
set_property -dict { PACKAGE_PIN B22 IOSTANDARD LVCMOS12 } [get_ports { btnc }]

## ADAU1761 audio codec (bank 34, LVCMOS33)
set_property -dict { PACKAGE_PIN U6 IOSTANDARD LVCMOS33 } [get_ports { ac_mclk }]
set_property -dict { PACKAGE_PIN T5 IOSTANDARD LVCMOS33 } [get_ports { ac_bclk }]
set_property -dict { PACKAGE_PIN U5 IOSTANDARD LVCMOS33 } [get_ports { ac_lrclk }]
set_property -dict { PACKAGE_PIN W6 IOSTANDARD LVCMOS33 } [get_ports { ac_dac_sdata }]

## Codec I2C — board has pull-ups; drive open-drain only.
set_property -dict { PACKAGE_PIN W5 IOSTANDARD LVCMOS33 } [get_ports { ac_scl }]
set_property -dict { PACKAGE_PIN V5 IOSTANDARD LVCMOS33 } [get_ports { ac_sda }]
set_property PULLTYPE PULLUP [get_ports { ac_scl }]
set_property PULLTYPE PULLUP [get_ports { ac_sda }]

## Status LEDs (LD0 leftmost) — see top_audio_beep_test.sv for the map.
set_property -dict { PACKAGE_PIN T14 IOSTANDARD LVCMOS25 } [get_ports { led[0] }]
set_property -dict { PACKAGE_PIN T15 IOSTANDARD LVCMOS25 } [get_ports { led[1] }]
set_property -dict { PACKAGE_PIN T16 IOSTANDARD LVCMOS25 } [get_ports { led[2] }]
set_property -dict { PACKAGE_PIN U16 IOSTANDARD LVCMOS25 } [get_ports { led[3] }]
set_property -dict { PACKAGE_PIN V15 IOSTANDARD LVCMOS25 } [get_ports { led[4] }]
set_property -dict { PACKAGE_PIN W16 IOSTANDARD LVCMOS25 } [get_ports { led[5] }]
set_property -dict { PACKAGE_PIN W15 IOSTANDARD LVCMOS25 } [get_ports { led[6] }]
set_property -dict { PACKAGE_PIN Y13 IOSTANDARD LVCMOS25 } [get_ports { led[7] }]

## The 12 MHz MCLK is generated by this design's own MMCM; the I2S clocks
## are simple divides of it inside the fabric, so no extra create_clock is
## needed. Async between clk100 and mclk is handled by the 2FF syncs.
set_false_path -from [get_clocks sys_clk_pin] -to [get_pins -hierarchical -filter {NAME =~ *done_sync_reg[0]*/D}] -quiet
