#!/usr/bin/env python3
"""Generate NAME.ARTJS — the Chrome-side art for a title, from NAME.ARTX.

Chrome is the control: opening storage/NAME.HTML must show what the machine
shows. The title's sprites live in NAME.ARTX as palette-indexed pixels, which
Chrome cannot read directly, so this writes a plain script that Chrome loads
with an ordinary <script src> tag:

    var __jmrSpr = ["data:image/png;base64,...", ...];

A classic <script src> works from file:// with no web server, which fetch()
and ES modules do not. That is the whole reason for this shape.

The images are rebuilt FROM THE ARTX, not from the artist's originals, so
Chrome previews the quantized art the machine will actually draw — a real
control, not an approximation of one.

The .ARTJS never goes on the card: the machine reads the .ARTX.

    python3 tools/make_artjs.py            # every title with an .ARTX
    python3 tools/make_artjs.py MYGAME --patch-html
"""

from __future__ import annotations

import argparse
import base64
import io
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from functional_model.jsb_format import read_artx  # noqa: E402

STORAGE = ROOT / "storage"


def artjs_for(artx: bytes) -> str:
    """One data: URL per sprite, expanded through the title palette."""
    from PIL import Image

    palette, sprites, _payload = read_artx(artx)
    urls: list[str] = []
    for w, h, pix in sprites:
        img = Image.new("RGBA", (w, h))
        out = []
        for idx in pix[: w * h]:
            r, g, b = palette[idx]
            # index 0 is the transparent slot, matching _quantize_sprites
            out.append((r, g, b, 0 if idx == 0 else 255))
        img.putdata(out)
        buf = io.BytesIO()
        img.save(buf, format="PNG")
        urls.append(
            "data:image/png;base64," + base64.b64encode(buf.getvalue()).decode()
        )
    body = ",\n".join(f'  "{u}"' for u in urls)
    return (
        "// Generated by tools/make_artjs.py from the title's .ARTX — do not\n"
        "// edit. Chrome-only; the machine reads the .ARTX itself.\n"
        f"var __jmrSpr = [\n{body}\n];\n"
    )


def shim_for(stem: str) -> str:
    """The two Chrome-only tags that make jmr:spr:N resolve in a browser.

    A classic <script src> is used deliberately: it loads from file:// with
    no web server, where fetch() and ES modules are blocked by CORS. The card
    mint strips data-host="chrome" blocks, so the machine never sees either.
    """
    return (
        f'<script data-host="chrome" src="{stem}.ARTJS"></script>\n'
        '<script data-host="chrome">\n'
        "// Chrome control: resolve the machine's sprite handles to the same\n"
        "// quantized art the machine draws.\n"
        "(function () {\n"
        '  if (typeof __jmrSpr === "undefined") { return; }\n'
        "  var d = Object.getOwnPropertyDescriptor("
        'HTMLImageElement.prototype, "src");\n'
        '  Object.defineProperty(HTMLImageElement.prototype, "src", {\n'
        "    get: function () { return d.get.call(this); },\n"
        "    set: function (v) {\n"
        "      var m = /^jmr:spr:(\\d+)$/.exec(String(v));\n"
        "      d.set.call(this, m ? (__jmrSpr[+m[1]] || v) : v);\n"
        "    }\n"
        "  });\n"
        "})();\n"
        "</script>\n"
    )


_PNG_SET = "d.set.call(this, m ? window.JMR_SPR[+m[1]] : v);"
_ART_SET = "d.set.call(this, m ? (__jmrSpr[+m[1]] || v) : v);"
_IIFE_OPEN = "(function () {\n  var d = Object.getOwnPropertyDescriptor"
_IIFE_GUARD = (
    "(function () {\n"
    '  if (typeof __jmrSpr === "undefined") { return; }\n'
    "  var d = Object.getOwnPropertyDescriptor"
)
# Minified one-liner (BOMBERMA): var P=window.JMR_SPR; ... m?P[+m[1]]:v
# Pretty-printed _PNG_SET does not match that, so Chrome kept loading PNGs.
_MIN_PNG_IIFE = re.compile(
    r"\(function\s*\(\)\s*\{\s*"
    r"var P\s*=\s*window\.JMR_SPR\s*;"
    r".*?"
    r"d\.set\.call\(this,\s*m\s*\?\s*P\[\+m\[1\]\]\s*:\s*v\)\s*;"
    r".*?"
    r"\}\)\s*\(\)\s*;",
    re.S,
)
_ARTJS_IIFE = (
    "(function () {\n"
    '  if (typeof __jmrSpr === "undefined") { return; }\n'
    "  var d = Object.getOwnPropertyDescriptor("
    'HTMLImageElement.prototype, "src");\n'
    '  Object.defineProperty(HTMLImageElement.prototype, "src", {\n'
    "    get: function () { return d.get.call(this); },\n"
    "    set: function (v) {\n"
    "      var m = /^jmr:spr:(\\d+)$/.exec(String(v));\n"
    "      d.set.call(this, m ? (__jmrSpr[+m[1]] || v) : v);\n"
    "    }\n"
    "  });\n"
    "})();"
)


def patch_html(stem: str) -> str:
    """Wire Chrome to NAME.ARTJS. Keep JMR_SPR as the make_artx.py manifest.

    Do not leave two src interceptors: the PNG rewrite becomes __jmrSpr.
    Idempotent. A title with no JMR_SPR shim still gets shim_for() inserted.
    """
    path = STORAGE / f"{stem}.HTML"
    if not path.is_file():
        return f"{stem:8s} no .HTML"
    html = path.read_text(encoding="utf-8")
    notes = []

    artjs_src = f'src="{stem}.ARTJS"'
    if artjs_src not in html and f"src='{stem}.ARTJS'" not in html:
        tag = f'<script data-host="chrome" src="{stem}.ARTJS"></script>\n'
        if "window.JMR_SPR" in html:
            i = html.find("<script")
            if i < 0:
                return f"{stem:8s} no script tag"
            html = html[:i] + tag + html[i:]
            notes.append("ARTJS src")
        else:
            i = html.find("<script")
            if i < 0:
                return f"{stem:8s} no script tag"
            path.write_text(html[:i] + shim_for(stem) + html[i:], encoding="utf-8")
            return f"{stem:8s} shim inserted before the title script"

    if _PNG_SET in html:
        html = html.replace(_PNG_SET, _ART_SET, 1)
        notes.append("interceptor → __jmrSpr")
    elif "__jmrSpr[+m" not in html:
        # lambda so (\d+) in the IIFE is not a re.sub backref
        html, nsub = _MIN_PNG_IIFE.subn(lambda _m: _ARTJS_IIFE, html, count=1)
        if nsub:
            notes.append("interceptor → __jmrSpr")

    if _ART_SET in html and 'typeof __jmrSpr === "undefined"' not in html:
        if _IIFE_OPEN in html:
            html = html.replace(_IIFE_OPEN, _IIFE_GUARD, 1)
            notes.append("ARTJS guard")

    if not notes:
        return f"{stem:8s} shim already present"
    path.write_text(html, encoding="utf-8")
    return f"{stem:8s} " + "; ".join(notes)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("names", nargs="*", help="title stems (default: all .ARTX)")
    ap.add_argument(
        "--patch-html",
        action="store_true",
        help="also insert the Chrome shim into storage/NAME.HTML (idempotent)",
    )
    args = ap.parse_args(argv)

    stems = [n.upper().removesuffix(".ARTX") for n in args.names]
    if not stems:
        stems = sorted(p.stem for p in STORAGE.glob("*.ARTX"))
    rc = 0
    for stem in stems:
        artx = STORAGE / f"{stem}.ARTX"
        if not artx.is_file():
            print(f"{stem:8s} no .ARTX")
            rc = 1
            continue
        js = artjs_for(artx.read_bytes())
        dest = STORAGE / f"{stem}.ARTJS"
        dest.write_text(js, encoding="utf-8")
        print(f"{stem:8s} -> {dest.name} ({len(js):,} bytes)")
        if args.patch_html:
            print("         " + patch_html(stem))
    return rc


if __name__ == "__main__":
    raise SystemExit(main())
